# Generated by Django 5.2.6 on 2025-09-27 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoArticulo',
            fields=[
                ('grupo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_grupo', models.CharField(max_length=10)),
                ('nombre_grupo', models.CharField(max_length=100)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
            ],
            options={
                'verbose_name': 'Grupo de Artículo',
                'verbose_name_plural': 'Grupos de Artículos',
                'db_table': 'grupos_articulos',
            },
        ),
        migrations.CreateModel(
            name='LineaArticulo',
            fields=[
                ('linea_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_linea', models.CharField(max_length=10)),
                ('nombre_linea', models.CharField(max_length=100)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grupos_lineas', to='core.grupoarticulo')),
            ],
            options={
                'verbose_name': 'Línea de Artículo',
                'verbose_name_plural': 'Líneas de Artículos',
                'db_table': 'lineas_articulos',
            },
        ),
    ]
